### PR TITLE
:books: Add Grist node and credentials docs

### PR DESCRIPTION
**Pull request by alexmojaki**
This goes with the new node being added in https://github.com/n8n-io/n8n/pull/2158

I wrote the docs based on https://docs.n8n.io/nodes/n8n-nodes-base.airtable/

### CODE REVIEW

**Comment by harshil1712** [comment]
Hey @alexmojaki!

Thank you for contributing the documentation. We will merge it once the node is merged ✨

**Comment by paulfitz** [comment]
It looks like the node got merged @harshil1712 🍾  https://github.com/n8n-io/n8n/pull/2158

**Comment by gpene** [comment]
Thanks @alexmojaki , once the node is released the docs will be published as well

**Comment by alexmojaki** [comment]
Thanks for releasing the node! https://n8n.io/integrations/n8n-nodes-base.grist

Since this isn't merged, the "Relevant links" predictably give 404s...

**Pull request merged**
