### PR TITLE
update apt-get update for hetzner

### PR DESCRIPTION
**Pull request by NoahBohme**
The default for Hetzner Cloud with Docker-CE is now Ubuntu 22.04 - Therefore the update command should be apt-get update

Also added apt-get upgrade.

### CODE REVIEW

**Comment by Joffcom** [comment]
@NoahBohme would you also accept just `apt update` and `apt upgrade` as these are the preferred commands for Ubuntu?

**Comment by NoahBohme** [comment]
Hi @Joffcom 
I was not able to run apt get update when booting up a Docker CE on Hetzner Cloud

**Comment by Joffcom** [comment]
Hey @NoahBohme,

That part doesn't surprise me and I think that was a typo that was not picked up on before, I believe the correct command should be `apt update` and `apt upgrade` without the other part. From what I remember while `apt-get` will work just `apt` has been preferred for a while.

**Comment by Joffcom** [comment]
@NoahBohme you could have updated the same PR if it was easier.

**Pull request closed without merging**
