### PR TITLE
📚 Add documentation for metrics endpoint

### PR DESCRIPTION
**Pull request by bacarini**
Documentation for the PR https://github.com/n8n-io/n8n/pull/1515

### CODE REVIEW

**Comment by janober** [comment]
Cool, thanks a lot! Only the environment variable is wrong. It got changed to `N8N_METRICS` as we try to keep the beginning identical for values that belong together.

**Comment by bacarini** [comment]
> Cool, thanks a lot! Only the environment variable is wrong. It got changed to `N8N_METRICS` as we try to keep the beginning identical for values that belong together.

**Comment by bacarini** [comment]
nice, I didn't notice
@janober I renamed the environment variable

**Comment by tanay1337** [comment]
Thanks a lot @bacarini, got merged! 🎉

**Pull request merged**
