### PR TITLE
DOC-1109: Update Gmail Trigger to high tier template

### PR DESCRIPTION
**Pull request by freakwriter**
Summary of changes:

- Moved Poll Times options into a snippet, since other triggers use the same setting.
- Added all parameters and options.
- Updated RSS feed read trigger to use same snippet.
- Added auth error.

### CODE REVIEW

**Comment by nik8n** [comment]
Let's also have a separate common issues page here. Felt much cleaner. It also feels like there's something wrong with the formating. The poll options now are under common issues

**Comment by nik8n** [comment]
The operations and options also still feel a little bit "much", no? Feel free to disagree

**Comment by freakwriter** [comment]
@nik8n "a bit much"...meaning you preferred the bullet point list instead of the separate headings? I can shift back to that.

**Comment by nik8n** [comment]
Sorry for the fluffy comms :D. With "a bit much" I mean the amount of content on the page. It felt a little chaotic to me with node params, node filters and all the different poll mode options being relatively close in section weights. I was thinking if we could/should hide some of this behind dedicated pages

**Comment by freakwriter** [comment]
Ahh okay, that makes more sense. The Poll section is the one that makes the page feel gigantic, I think. Let me try moving that to its own page first and see what that looks like.

**Comment by freakwriter** [comment]
@nik8n with the poll mode options on a new page, this one feels a lot more manageable (I also reverted the separate headings per parameter/option in case that was causing some of the visual overload). Let me know what you think.

**Review by nik8n — APPROVED** [review]
Yes, much better. Thank you!

**Pull request merged**
