### PR TITLE
Removed useless numbers (typos)

### PR DESCRIPTION
**Pull request by albertopasqualetto**
Those numbers are also in the images

### CODE REVIEW

**Comment by StarfallProjects** [comment]
@albertopasqualetto thanks for the contribution! However, these are not 'useless' numbers: this example contains three different todo nodes, so the numbers in their names differentiate them.

Ideally this example would be overhauled to use more meaningful names, as well as follow the [style guide](https://github.com/n8n-io/n8n-docs/wiki/Styles). If you feel like taking that on, that'd be awesome!

Closing this for now.

**Comment by albertopasqualetto** [comment]
Maybe I am not understanding something but in my version of n8n (updated at time of this PR) the node is only one and it can be set to get, update,...
Since get and update already differentiated them, the numbers were unnecessary.
What am I not getting?

**Comment by StarfallProjects** [comment]
In the example you updated, three copies of the node are added to the workflow, hence them needing different names. You can't have multiple nodes with the same name on the canvas. If you follow the tutorial, you will see these are the names automatically created when you add more nodes.

However, the example is out of date in other ways now, so probably does need a rewrite or removal.

**Comment by albertopasqualetto** [comment]
I understand now

**Pull request closed without merging**
