### PR TITLE
Update user-management.md

### PR DESCRIPTION
**Pull request by codezz**
it gives an error with caps SMTP

### CODE REVIEW

**Review by StarfallProjects — APPROVED** [review]

**Comment by StarfallProjects** [comment]
@codezz thanks for this! Looks good, but we can't merge until you sign the contributor license agreement.

**Comment by StarfallProjects** [comment]
@codezz I felt we needed to get this fix out, and we can't merge this without the agreement being signed, so I went ahead and made the change myself. Thank you for flagging the issue!

**Comment by codezz** [comment]
Great. I can't sign that since there is no action to take on the page :)

**Comment by codezz** [comment]
@StarfallProjects

**Comment by StarfallProjects** [comment]
@codezz Thank you for letting us know, I'll raise this. Could you tell me what browser you're in?

**Comment by codezz** [comment]
Sure, Brave Browser on Android phone.

**Comment by StarfallProjects** [comment]
@codezz Cheers. As far as we can see everything is set up ok our end (and we haven't had any other reports) This task uses an external service, so possibly a glitch their end (hopefully temporary, as you were able to sign eventually) We'll keep an eye on this in case of further reports. Sorry about the bumpy experience.

**Pull request closed without merging**
