### PR TITLE
added docs for Plivo node

### PR DESCRIPTION
**Pull request by nixonsam**

### CODE REVIEW

**Comment by nixonsam** [comment]
@tanay1337 Please check this and merge. Thanks!

**Comment by harshil1712** [comment]
Hey @nixonsam!

Thank you for your contribution ❤️ 

I've made some changes and created a PR #460

**Comment by nixonsam** [comment]
thank you @harshil1712

**Comment by tanay1337** [comment]
Merged, thanks a lot for contributing @nixonsam. Can't wait to play around with n8n and Plivo 😍

**Comment by nixonsam** [comment]
thanks a lot @tanay1337 !

**Pull request merged**
