### PR TITLE
fix apt update and update to upgrade

### PR DESCRIPTION
**Pull request by NoahBohme**
change to apt update and also include upgrade.
Fix type

### CODE REVIEW

**Comment by Joffcom** [comment]
@NoahBohme nice touch with the `-y`, don't forget to complete the CLA step so we can merge this 🙌

**Review by Lamoaw2 — APPROVED** [review]
434859N70435435903Q
534508N3Q75
9345

**Comment by Lamoaw2** [comment]
34534 534N5
630457843534
05N8 348 63476935870N653

**Comment by Joffcom** [comment]
Hey @NoahBohme,

As this change was good but the CLA hasn't been signed I have recreated it here: https://github.com/n8n-io/n8n-docs/pull/1445 under my own user so we can get it merged.

Thanks for your contribution.

**Pull request closed without merging**
